"""add is_viewable

Revision ID: 6756a6a19a92
Revises: 7777cde44aac
Create Date: 2025-11-12 19:56:41.345300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6756a6a19a92'
down_revision = '7777cde44aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_viewable', sa.Boolean(), server_default='TRUE', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('is_viewable')

    # ### end Alembic commands ###
