"""add soft delete

Revision ID: 7777cde44aac
Revises: dd25ebc37dcf
Create Date: 2025-11-11 22:01:03.031869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7777cde44aac'
down_revision = 'dd25ebc37dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=False))
        batch_op.add_column(sa.Column('date_deleted', sa.Date(), nullable=True))

    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=False))
        batch_op.add_column(sa.Column('date_deleted', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('date_deleted')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('date_deleted')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
