"""add_user_id_to_artist

Revision ID: dd25ebc37dcf
Revises: c8d9e5f6a7b8
Create Date: 2025-11-05 06:26:57.383763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd25ebc37dcf'
down_revision = 'c8d9e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.alter_column('storage_id',
               existing_type=sa.CHAR(length=8),
               type_=sa.CHAR(length=7),
               existing_nullable=False)

    with op.batch_alter_table('artwork_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artwork_photos_artwork_num'))
        batch_op.drop_index(batch_op.f('ix_artwork_photos_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_artwork_photos_uploaded_by'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artwork_photos_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_photos_uploaded_at'), ['uploaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artwork_photos_artwork_num'), ['artwork_num'], unique=False)

    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.alter_column('storage_id',
               existing_type=sa.CHAR(length=7),
               type_=sa.CHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
